name: tcompro_customer
description: "Tcompro Customer Application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.11.0-55.0.dev

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  supabase_flutter: ^2.0.0
  dio: ^5.0.0
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter:
  assets:
    - .env
  uses-material-design: true
